// 30+ Curated Demo Products for Mini Daraz across 15 Pakistani categories

const INITIAL_CATEGORIES = [
    { id: 'mobile-phones', name: 'Mobile Phones', icon: 'fa-mobile-screen', count: 6 },
    { id: 'laptops-computers', name: 'Laptops & Computers', icon: 'fa-laptop', count: 4 },
    { id: 'headphones-audio', name: 'Headphones & Audio', icon: 'fa-headphones', count: 4 },
    { id: 'smart-watches', name: 'Smart Watches', icon: 'fa-clock', count: 3 },
    { id: 'gaming', name: 'Gaming & Consoles', icon: 'fa-gamepad', count: 3 },
    { id: 'tv-electronics', name: 'TVs & Appliances', icon: 'fa-tv', count: 3 },
    { id: 'mens-fashion', name: 'Men’s Fashion', icon: 'fa-shirt', count: 3 },
    { id: 'womens-fashion', name: 'Women’s Fashion', icon: 'fa-vest-patches', count: 3 },
    { id: 'shoes-footwear', name: 'Shoes & Footwear', icon: 'fa-shoe-prints', count: 3 },
    { id: 'bags-luggage', name: 'Bags & Luggage', icon: 'fa-bag-shopping', count: 2 },
    { id: 'beauty-care', name: 'Beauty & Skincare', icon: 'fa-spa', count: 3 },
    { id: 'home-kitchen', name: 'Home & Kitchen', icon: 'fa-kitchen-set', count: 3 },
    { id: 'sports-fitness', name: 'Sports & Fitness', icon: 'fa-baseball-bat-ball', count: 3 },
    { id: 'books-stationery', name: 'Books & Stationery', icon: 'fa-book-open', count: 2 },
    { id: 'accessories', name: 'Accessories & Tools', icon: 'fa-plug', count: 3 }
];

const INITIAL_SELLERS = [
    { id: 'seller-1', name: 'TechZone Official Mall', city: 'Lahore', rating: 4.9, positiveRate: '99%', responseRate: '100%', joined: '2021', verified: true },
    { id: 'seller-2', name: 'Karachi Electronics Hub', city: 'Karachi', rating: 4.8, positiveRate: '97%', responseRate: '98%', joined: '2022', verified: true },
    { id: 'seller-3', name: 'Islamabad Gadgets Store', city: 'Islamabad', rating: 4.9, positiveRate: '99%', responseRate: '99%', joined: '2020', verified: true },
    { id: 'seller-4', name: 'Rawalpindi Mobile Point', city: 'Rawalpindi', rating: 4.7, positiveRate: '95%', responseRate: '96%', joined: '2023', verified: true },
    { id: 'seller-5', name: 'Pak Heritage Fashion', city: 'Faisalabad', rating: 4.8, positiveRate: '98%', responseRate: '97%', joined: '2021', verified: true },
    { id: 'seller-6', name: 'Multan Sports Arena', city: 'Multan', rating: 4.9, positiveRate: '99%', responseRate: '100%', joined: '2022', verified: true }
];

const INITIAL_PRODUCTS = [
    {
        id: 'prod-001',
        title: 'Samsung Galaxy S24 Ultra (12GB RAM / 256GB Titanium Gray - PTA Approved)',
        slug: 'samsung-galaxy-s24-ultra-pta',
        category: 'mobile-phones',
        brand: 'Samsung',
        price: 389999,
        oldPrice: 429999,
        discount: 9,
        rating: 4.9,
        reviewsCount: 342,
        stock: 14,
        sellerName: 'TechZone Official Mall',
        sellerCity: 'Lahore',
        imageUrl: 'https://images.unsplash.com/photo-1610945265064-0e34e5519bbf?auto=format&fit=crop&w=800&q=80',
        additionalImages: [
            'https://images.unsplash.com/photo-1580910051074-3eb694886505?auto=format&fit=crop&w=800&q=80',
            'https://images.unsplash.com/photo-1598327105666-5b89351aff97?auto=format&fit=crop&w=800&q=80'
        ],
        description: 'Experience groundbreaking Galaxy AI, ultra-vivid 200MP camera system, titanium body, and built-in S-Pen. Fully official PTA approved with 1 Year Official Samsung Pakistan Warranty.',
        specifications: {
            'Display': '6.8" Dynamic LTPO AMOLED 2X 120Hz',
            'Processor': 'Snapdragon 8 Gen 3 for Galaxy',
            'Camera': '200MP Quad Rear + 12MP Selfie',
            'Battery': '5000 mAh with 45W Fast Charging',
            'PTA Status': '100% Official PTA Approved',
            'Warranty': '1 Year Official Brand Warranty'
        },
        colors: ['Titanium Gray', 'Titanium Black', 'Titanium Violet'],
        isFlashSale: true,
        isTrending: true,
        isRecommended: true,
        reviews: [
            { id: 'rev-1', name: 'Hamza Khan', city: 'Islamabad', rating: 5, date: '2026-08-15', comment: 'Original sealed box received in Islamabad within 24 hours. PTA approved verified on CDIR!' },
            { id: 'rev-2', name: 'Zeeshan Ali', city: 'Lahore', rating: 5, date: '2026-08-20', comment: 'Galaxy AI features are unreal. Night photography is top notch. Highly recommended seller!' }
        ]
    },
    {
        id: 'prod-002',
        title: 'Xiaomi Redmi Note 13 Pro 4G (8GB/256GB - 200MP Camera - 67W Turbo Charge)',
        slug: 'xiaomi-redmi-note-13-pro',
        category: 'mobile-phones',
        brand: 'Xiaomi',
        price: 64999,
        oldPrice: 74999,
        discount: 13,
        rating: 4.8,
        reviewsCount: 520,
        stock: 35,
        sellerName: 'Karachi Electronics Hub',
        sellerCity: 'Karachi',
        imageUrl: 'https://images.unsplash.com/photo-1511707171634-5f897ff02aa9?auto=format&fit=crop&w=800&q=80',
        additionalImages: [
            'https://images.unsplash.com/photo-1565849904461-04a58ad377e0?auto=format&fit=crop&w=800&q=80'
        ],
        description: 'Redmi Note 13 Pro delivers stunning 200MP OIS camera clarity, ultra-smooth 120Hz AMOLED display, in-display fingerprint sensor, and lightning-fast 67W charging in the box.',
        specifications: {
            'Display': '6.67" AMOLED FHD+ 120Hz Corning Gorilla Glass 5',
            'Memory': '8GB RAM + 256GB Internal Storage',
            'Primary Camera': '200MP Ultra-Clear with OIS',
            'Battery': '5000 mAh + 67W Turbo Charger Included',
            'PTA Status': 'Official PTA Approved',
            'Warranty': '1 Year Airlink Pakistan Warranty'
        },
        colors: ['Midnight Black', 'Forest Green', 'Ocean Blue'],
        isFlashSale: true,
        isTrending: true,
        isRecommended: true,
        reviews: [
            { id: 'rev-3', name: 'Bilal Ahmed', city: 'Karachi', rating: 5, date: '2026-07-22', comment: 'Best phone in this price bracket in Pakistan. Battery lasts 1.5 days easily.' }
        ]
    },
    {
        id: 'prod-003',
        title: 'Apple iPhone 15 (128GB - Official PTA Approved - 1 Year Mercantile Warranty)',
        slug: 'apple-iphone-15-pta',
        category: 'mobile-phones',
        brand: 'Apple',
        price: 324999,
        oldPrice: 359999,
        discount: 10,
        rating: 4.9,
        reviewsCount: 180,
        stock: 8,
        sellerName: 'Islamabad Gadgets Store',
        sellerCity: 'Islamabad',
        imageUrl: 'https://images.unsplash.com/photo-1695048133142-1a20484d2569?auto=format&fit=crop&w=800&q=80',
        additionalImages: [
            'https://images.unsplash.com/photo-1591337676887-a217a6970a8a?auto=format&fit=crop&w=800&q=80'
        ],
        description: 'Dynamic Island, 48MP main camera with 2x Telephoto, durable color-infused glass design, USB-C connector and all-day battery life.',
        specifications: {
            'Display': '6.1" Super Retina XDR OLED Display',
            'Chipset': 'A16 Bionic Chip with 5-core GPU',
            'Camera': 'Advanced Dual-Camera (48MP Main + 12MP Ultra Wide)',
            'PTA Status': 'Official PTA Tax Paid',
            'Warranty': '1 Year Mercantile Pakistan Official Warranty'
        },
        colors: ['Black', 'Blue', 'Pink', 'Green'],
        isFlashSale: false,
        isTrending: true,
        isRecommended: true,
        reviews: [
            { id: 'rev-4', name: 'Sara Tariq', city: 'Lahore', rating: 5, date: '2026-08-11', comment: '100% genuine pin-pack device. Camera is breathtaking and lightweight.' }
        ]
    },
    {
        id: 'prod-004',
        title: 'Infinix Note 40 Pro (12GB RAM / 256GB - 70W All-Round FastCharge 2.0)',
        slug: 'infinix-note-40-pro',
        category: 'mobile-phones',
        brand: 'Infinix',
        price: 68999,
        oldPrice: 75999,
        discount: 9,
        rating: 4.7,
        reviewsCount: 290,
        stock: 22,
        sellerName: 'Rawalpindi Mobile Point',
        sellerCity: 'Rawalpindi',
        imageUrl: 'https://images.unsplash.com/photo-1574944985070-8f3ebc6b79d2?auto=format&fit=crop&w=800&q=80',
        additionalImages: [],
        description: 'Features 3D-Curved 120Hz AMOLED Screen, 108MP OIS Super-Zoom Camera, Wireless MagCharge support, and dual JBL tuned speakers.',
        specifications: {
            'Screen': '6.78" 3D Curved 120Hz AMOLED',
            'RAM/Storage': '12GB (+12GB Extended) / 256GB ROM',
            'Charging': '70W Wired + 20W Wireless MagCharge',
            'Warranty': '1 Year Carlcare Pakistan Warranty'
        },
        colors: ['Vintage Green', 'Titan Gold'],
        isFlashSale: true,
        isTrending: false,
        isRecommended: true,
        reviews: []
    },
    {
        id: 'prod-005',
        title: 'Apple MacBook Air 13.6" M2 Chip (8-Core CPU / 8-Core GPU / 8GB / 256GB SSD - Space Gray)',
        slug: 'macbook-air-m2-space-gray',
        category: 'laptops-computers',
        brand: 'Apple',
        price: 279999,
        oldPrice: 310000,
        discount: 10,
        rating: 4.9,
        reviewsCount: 145,
        stock: 10,
        sellerName: 'TechZone Official Mall',
        sellerCity: 'Lahore',
        imageUrl: 'https://images.unsplash.com/photo-1517336714731-489689fd1ca8?auto=format&fit=crop&w=800&q=80',
        additionalImages: [
            'https://images.unsplash.com/photo-1611186871348-b1ce696e52c9?auto=format&fit=crop&w=800&q=80'
        ],
        description: 'Strikingly thin design with up to 18 hours of battery life. Liquid Retina display, 1080p FaceTime HD camera, and spatial audio speakers.',
        specifications: {
            'Processor': 'Apple M2 chip 8-core CPU / 8-core GPU',
            'Display': '13.6-inch Liquid Retina Display with True Tone',
            'Memory': '8GB Unified Memory',
            'Storage': '256GB Ultra-Fast SSD',
            'Battery': 'Up to 18 Hours battery life',
            'Warranty': '1 Year Apple International Warranty'
        },
        colors: ['Space Gray', 'Silver', 'Midnight', 'Starlight'],
        isFlashSale: true,
        isTrending: true,
        isRecommended: true,
        reviews: [
            { id: 'rev-5', name: 'Usman Ghani', city: 'Faisalabad', rating: 5, date: '2026-08-01', comment: 'Super fast laptop for coding and video editing. Super silent with zero fan noise.' }
        ]
    },
    {
        id: 'prod-006',
        title: 'HP Victus 15 Gaming Laptop (Intel Core i5 13th Gen, 16GB DDR4, 512GB NVMe, RTX 3050 6GB)',
        slug: 'hp-victus-15-gaming-rtx3050',
        category: 'laptops-computers',
        brand: 'HP',
        price: 214999,
        oldPrice: 239999,
        discount: 10,
        rating: 4.8,
        reviewsCount: 98,
        stock: 12,
        sellerName: 'Karachi Electronics Hub',
        sellerCity: 'Karachi',
        imageUrl: 'https://images.unsplash.com/photo-1603302576837-37561b2e2302?auto=format&fit=crop&w=800&q=80',
        additionalImages: [],
        description: 'Dominate your favourite PC games like GTA V, Cyberpunk, and Valorant with high frame rates on a 144Hz IPS display and dedicated NVIDIA RTX graphics.',
        specifications: {
            'Processor': 'Intel Core i5-13420H (Up to 4.6GHz Turbo)',
            'Graphics': 'NVIDIA GeForce RTX 3050 (6GB Dedicated GDDR6)',
            'RAM': '16GB DDR4 3200MHz',
            'Storage': '512GB PCIe NVMe M.2 SSD',
            'Display': '15.6" Full HD 144Hz IPS Anti-Glare',
            'Warranty': '1 Year Local HP Pakistan Warranty'
        },
        colors: ['Mica Silver', 'Performance Blue'],
        isFlashSale: false,
        isTrending: true,
        isRecommended: true,
        reviews: []
    },
    {
        id: 'prod-007',
        title: 'Audionic Airbud 550 Wireless TWS Earbuds (Quad Mic ENC - Low Latency Gaming Mode)',
        slug: 'audionic-airbud-550-wireless',
        category: 'headphones-audio',
        brand: 'Audionic',
        price: 4299,
        oldPrice: 6500,
        discount: 34,
        rating: 4.7,
        reviewsCount: 812,
        stock: 80,
        sellerName: 'TechZone Official Mall',
        sellerCity: 'Lahore',
        imageUrl: 'https://images.unsplash.com/photo-1590658268037-6bf12165a8df?auto=format&fit=crop&w=800&q=80',
        additionalImages: [
            'https://images.unsplash.com/photo-1572536147248-ac59a8abfa4b?auto=format&fit=crop&w=800&q=80'
        ],
        description: 'Audionic Pakistan’s flagship Airbuds 550 with Quad Mic Environmental Noise Cancellation (ENC), 45ms ultra low latency gaming mode, and 30 hours total playtime.',
        specifications: {
            'Bluetooth': 'v5.3 Fast Pair with Auto Connect',
            'Playtime': 'Up to 30 Hours with Type-C Case',
            'Noise Cancellation': 'Quad Mic ENC for Crystal Clear Calls',
            'Water Resistance': 'IPX4 Splash Proof',
            'Warranty': '1 Year Official Audionic Pakistan Warranty'
        },
        colors: ['Classic White', 'Matte Black', 'Navy Blue'],
        isFlashSale: true,
        isTrending: true,
        isRecommended: true,
        reviews: [
            { id: 'rev-6', name: 'Noman Riaz', city: 'Rawalpindi', rating: 5, date: '2026-08-19', comment: 'Super deep bass, calling quality in traffic is unexpectedly crystal clear.' }
        ]
    },
    {
        id: 'prod-008',
        title: 'Sony WH-1000XM5 Wireless Noise-Cancelling Over-Ear Headphones (Silver)',
        slug: 'sony-wh-1000xm5-headphones',
        category: 'headphones-audio',
        brand: 'Sony',
        price: 98999,
        oldPrice: 115000,
        discount: 14,
        rating: 4.9,
        reviewsCount: 165,
        stock: 9,
        sellerName: 'Islamabad Gadgets Store',
        sellerCity: 'Islamabad',
        imageUrl: 'https://images.unsplash.com/photo-1505740420928-5e560c06d30e?auto=format&fit=crop&w=800&q=80',
        additionalImages: [],
        description: 'Industry-leading noise cancellation with two processors and 8 microphones. Hi-Res Audio wireless, 30-hour battery life, and crystal-clear hands-free calling.',
        specifications: {
            'Driver': '30mm specially designed carbon-fiber composite',
            'Battery': '30 Hours (NC ON), 3-min quick charge for 3 hours',
            'Weight': '250 grams ultra-comfortable lightweight fit',
            'Warranty': '1 Year Official Brand Warranty'
        },
        colors: ['Platinum Silver', 'Midnight Black'],
        isFlashSale: false,
        isTrending: true,
        isRecommended: true,
        reviews: []
    },
    {
        id: 'prod-009',
        title: 'Soundpeats Free2 Classic Wireless Earbuds (Dust & Water Resistant - 30H Playtime)',
        slug: 'soundpeats-free2-classic',
        category: 'headphones-audio',
        brand: 'Soundpeats',
        price: 5499,
        oldPrice: 7999,
        discount: 31,
        rating: 4.8,
        reviewsCount: 430,
        stock: 45,
        sellerName: 'Karachi Electronics Hub',
        sellerCity: 'Karachi',
        imageUrl: 'https://images.unsplash.com/photo-1608156639585-b3a032ef9689?auto=format&fit=crop&w=800&q=80',
        additionalImages: [],
        description: 'Laser-engraved leather texture design, 6mm biomechanical diaphragm driver for balanced audio, IPX5 waterproof rating, and Type-C quick charging.',
        specifications: {
            'Battery': '8 Hours single charge + 22 Hours charging case',
            'Waterproof': 'IPX5 Sweat & Water Resistant',
            'Controls': 'Smart Touch Control',
            'Warranty': '6 Months Replacement Warranty'
        },
        colors: ['Black'],
        isFlashSale: true,
        isTrending: false,
        isRecommended: true,
        reviews: []
    },
    {
        id: 'prod-010',
        title: 'Dany Rex Pro Bluetooth Calling Smart Watch (1.96" HD AMOLED Screen - Metallic Body)',
        slug: 'dany-rex-pro-smart-watch',
        category: 'smart-watches',
        brand: 'Dany',
        price: 6999,
        oldPrice: 10500,
        discount: 33,
        rating: 4.6,
        reviewsCount: 312,
        stock: 60,
        sellerName: 'TechZone Official Mall',
        sellerCity: 'Lahore',
        imageUrl: 'https://images.unsplash.com/photo-1523275335684-37898b6baf30?auto=format&fit=crop&w=800&q=80',
        additionalImages: [
            'https://images.unsplash.com/photo-1508685096489-7aacd43bd3b1?auto=format&fit=crop&w=800&q=80'
        ],
        description: 'Premium Pakistani smartwatch with full Bluetooth phone calling, heart rate & SpO2 health tracking, 100+ sports modes, wireless magnetic charging, and dual straps in box.',
        specifications: {
            'Display': '1.96" HD 3D Curved Color Touchscreen',
            'Calling': 'Built-in Speaker & HD Mic for Phone Calls',
            'Sensors': 'Real-Time Heart Rate, SpO2, Sleep Monitor',
            'Battery': 'Up to 7 Days Normal Use / 15 Days Standby',
            'Warranty': '1 Year Dany Pakistan Official Warranty'
        },
        colors: ['Space Gray Metal', 'Rose Gold', 'Silver Steel'],
        isFlashSale: true,
        isTrending: true,
        isRecommended: true,
        reviews: [
            { id: 'rev-7', name: 'Kashif Mehmood', city: 'Multan', rating: 5, date: '2026-08-14', comment: 'Battery timing is unbelievable. Calling dialer works smoothly with my Android.' }
        ]
    },
    {
        id: 'prod-011',
        title: 'Amazfit GTR 4 Smartwatch with Dual-Band GPS & 14-Day Battery (Black)',
        slug: 'amazfit-gtr-4-smartwatch',
        category: 'smart-watches',
        brand: 'Amazfit',
        price: 49999,
        oldPrice: 58000,
        discount: 14,
        rating: 4.9,
        reviewsCount: 110,
        stock: 15,
        sellerName: 'Islamabad Gadgets Store',
        sellerCity: 'Islamabad',
        imageUrl: 'https://images.unsplash.com/photo-1546868871-7041f2a55e12?auto=format&fit=crop&w=800&q=80',
        additionalImages: [],
        description: 'Ultra-accurate GPS positioning with circular polarized GPS antenna, 150+ sports modes, 1.43" HD AMOLED display, and Zepp OS 2.0.',
        specifications: {
            'Display': '1.43" AMOLED 466x466 326 PPI Anti-fingerprint Glass',
            'Battery': '475 mAh (14 Days standard usage)',
            'Water Resistance': '5 ATM (50 meters swim-proof)',
            'Warranty': '1 Year Official Warranty'
        },
        colors: ['Superspeed Black', 'Vintage Brown Leather'],
        isFlashSale: false,
        isTrending: true,
        isRecommended: false,
        reviews: []
    },
    {
        id: 'prod-012',
        title: 'Sony PlayStation 5 Console (Slim Disc Edition - 1TB SSD - Japanese Model)',
        slug: 'sony-ps5-slim-disc-edition',
        category: 'gaming',
        brand: 'Sony',
        price: 169999,
        oldPrice: 189999,
        discount: 11,
        rating: 5.0,
        reviewsCount: 220,
        stock: 7,
        sellerName: 'Karachi Electronics Hub',
        sellerCity: 'Karachi',
        imageUrl: 'https://images.unsplash.com/photo-1606813907291-d86efa9b94db?auto=format&fit=crop&w=800&q=80',
        additionalImages: [
            'https://images.unsplash.com/photo-1607604276583-eef5d076aa5f?auto=format&fit=crop&w=800&q=80'
        ],
        description: 'Experience lightning-fast loading with an ultra-high speed 1TB SSD, deeper immersion with haptic feedback, adaptive triggers, and 3D Audio.',
        specifications: {
            'Storage': '1TB Custom Ultra-High Speed NVMe SSD',
            'Video': '4K 120Hz / 8K Support with Ray Tracing',
            'In Box': 'PS5 Slim Disc Console, DualSense Wireless Controller, Cables',
            'Warranty': '1 Year Shop Hardware Warranty'
        },
        colors: ['Standard White'],
        isFlashSale: true,
        isTrending: true,
        isRecommended: true,
        reviews: [
            { id: 'rev-8', name: 'Saad Farooq', city: 'Karachi', rating: 5, date: '2026-08-05', comment: 'Fastest delivery in Karachi! Box was factory sealed with brand new condition.' }
        ]
    },
    {
        id: 'prod-013',
        title: 'Logitech G502 HERO High Performance Gaming Mouse (25K Sensor - RGB Lightsync)',
        slug: 'logitech-g502-hero-mouse',
        category: 'gaming',
        brand: 'Logitech',
        price: 13999,
        oldPrice: 17500,
        discount: 20,
        rating: 4.9,
        reviewsCount: 540,
        stock: 30,
        sellerName: 'TechZone Official Mall',
        sellerCity: 'Lahore',
        imageUrl: 'https://images.unsplash.com/photo-1615663245857-ac93bb7c39e7?auto=format&fit=crop&w=800&q=80',
        additionalImages: [],
        description: 'The world’s most popular gaming mouse equipped with HERO 25K optical sensor, 11 customizable buttons, adjustable weight system, and programmable RGB.',
        specifications: {
            'Sensor': 'HERO 25,600 Max DPI with zero smoothing',
            'Buttons': '11 Programmable Buttons with hyper-fast scroll',
            'Weights': '5 removable 3.6g weights included',
            'Warranty': '2 Years Official Logitech Warranty'
        },
        colors: ['Black'],
        isFlashSale: false,
        isTrending: true,
        isRecommended: true,
        reviews: []
    },
    {
        id: 'prod-014',
        title: 'Haier 55" 4K UHD Bezel-Less Google Android Smart LED TV (Dolby Vision & Atmos)',
        slug: 'haier-55-inch-4k-uhd-smart-led',
        category: 'tv-electronics',
        brand: 'Haier',
        price: 129999,
        oldPrice: 145000,
        discount: 10,
        rating: 4.8,
        reviewsCount: 88,
        stock: 11,
        sellerName: 'Karachi Electronics Hub',
        sellerCity: 'Karachi',
        imageUrl: 'https://images.unsplash.com/photo-1593359677879-a4bb92f829d1?auto=format&fit=crop&w=800&q=80',
        additionalImages: [],
        description: 'Certified Google TV with hands-free voice control, MEMC motion clarity, Dolby Vision HDR, Dolby Atmos sound, and preloaded Netflix, Prime Video and YouTube.',
        specifications: {
            'Screen Size': '55 Inch Ultra HD 4K (3840 x 2160)',
            'OS': 'Official Google TV OS with Play Store',
            'Audio': '30W Stereo Speakers with Dolby Atmos',
            'Warranty': '3 Years Panel + 1 Year Parts Official Haier Pakistan Warranty'
        },
        colors: ['Metallic Black Bezel-Less'],
        isFlashSale: false,
        isTrending: true,
        isRecommended: true,
        reviews: []
    },
    {
        id: 'prod-015',
        title: 'J. Junaid Jamshed Men’s Embroidered Cotton Kurta (Festive Eid Edition - Stitched)',
        slug: 'junaid-jamshed-men-embroidered-kurta',
        category: 'mens-fashion',
        brand: 'J. Junaid Jamshed',
        price: 4990,
        oldPrice: 6500,
        discount: 23,
        rating: 4.8,
        reviewsCount: 380,
        stock: 50,
        sellerName: 'Pak Heritage Fashion',
        sellerCity: 'Faisalabad',
        imageUrl: 'https://images.unsplash.com/photo-1602810318383-e386cc2a3ccf?auto=format&fit=crop&w=800&q=80',
        additionalImages: [
            'https://images.unsplash.com/photo-1617137984095-74e4e5e3613f?auto=format&fit=crop&w=800&q=80'
        ],
        description: 'Crafted from premium 100% fine cotton yarn with delicate collar & placket thread embroidery. Perfect for Jummah prayers, weddings, and Eid festivities.',
        specifications: {
            'Fabric': '100% Premium Egyptian Cotton',
            'Fit': 'Regular Fit Comfort Silhouette',
            'Care': 'Machine Wash Mild / Warm Iron',
            'Sizes': 'S, M, L, XL, XXL'
        },
        colors: ['Off-White', 'Navy Blue', 'Olive Green', 'Charcoal'],
        isFlashSale: true,
        isTrending: true,
        isRecommended: true,
        reviews: [
            { id: 'rev-9', name: 'Ahsan Qureshi', city: 'Lahore', rating: 5, date: '2026-08-08', comment: 'Top tier cotton fabric. Fitting is 100% accurate as per chart.' }
        ]
    },
    {
        id: 'prod-016',
        title: 'Alkaram Studio Women’s 3-Piece Printed Lawn Suit with Chiffon Dupatta',
        slug: 'alkaram-women-3piece-lawn-suit',
        category: 'womens-fashion',
        brand: 'Alkaram Studio',
        price: 5490,
        oldPrice: 7990,
        discount: 31,
        rating: 4.9,
        reviewsCount: 610,
        stock: 40,
        sellerName: 'Pak Heritage Fashion',
        sellerCity: 'Faisalabad',
        imageUrl: 'https://images.unsplash.com/photo-1583391733956-3750e0ff4e8b?auto=format&fit=crop&w=800&q=80',
        additionalImages: [],
        description: 'Vibrant digital floral printed lawn shirt paired with matching dyed cambric trousers and lightweight breezy chiffon dupatta for Pakistani summer & spring.',
        specifications: {
            'Shirt': 'Digital Printed Premium Lawn (3.0 Meters)',
            'Dupatta': 'Printed Crinkle Chiffon (2.5 Meters)',
            'Trouser': 'Dyed Cambric Cotton (2.5 Meters)',
            'Season': 'Spring / Summer 2026'
        },
        colors: ['Mustard Floral', 'Pastel Pink', 'Sky Blue'],
        isFlashSale: true,
        isTrending: true,
        isRecommended: true,
        reviews: [
            { id: 'rev-10', name: 'Fatima Zahra', city: 'Islamabad', rating: 5, date: '2026-08-16', comment: 'Color is 100% fast, doesn’t fade after multiple washes. Very soft dupatta.' }
        ]
    },
    {
        id: 'prod-017',
        title: 'Servis Men’s Genuine Leather Penny Loafers (Handcrafted Casual & Formal)',
        slug: 'servis-men-leather-penny-loafers',
        category: 'shoes-footwear',
        brand: 'Servis Shoes',
        price: 5999,
        oldPrice: 8500,
        discount: 29,
        rating: 4.7,
        reviewsCount: 215,
        stock: 35,
        sellerName: 'Pak Heritage Fashion',
        sellerCity: 'Faisalabad',
        imageUrl: 'https://images.unsplash.com/photo-1533867617858-e7b97e060509?auto=format&fit=crop&w=800&q=80',
        additionalImages: [],
        description: 'Made from genuine cowhide leather with cushioned memory foam insole and slip-resistant TPR rubber sole. Easy slip-on design for work or casual outings.',
        specifications: {
            'Upper Material': '100% Full Grain Genuine Cow Leather',
            'Insole': 'High-Density Memory Foam Cushioning',
            'Sole': 'Anti-Skid Flexible Rubber Outsole',
            'Origin': 'Made in Pakistan (Sialkot / Gujrat)'
        },
        colors: ['Tan Brown', 'Classic Black'],
        isFlashSale: false,
        isTrending: true,
        isRecommended: true,
        reviews: []
    },
    {
        id: 'prod-018',
        title: 'Stylo Women’s Quilted Crossbody Chain Shoulder Bag (Gold Hardware)',
        slug: 'stylo-quilted-crossbody-chain-bag',
        category: 'bags-luggage',
        brand: 'Stylo',
        price: 3850,
        oldPrice: 5200,
        discount: 26,
        rating: 4.8,
        reviewsCount: 195,
        stock: 28,
        sellerName: 'Pak Heritage Fashion',
        sellerCity: 'Faisalabad',
        imageUrl: 'https://images.unsplash.com/photo-1584917865442-de89df76afd3?auto=format&fit=crop&w=800&q=80',
        additionalImages: [],
        description: 'Chic quilted finish with luxury gold metallic chain strap and turn-lock closure. Spacious dual internal compartments for smartphone, makeup, keys and wallet.',
        specifications: {
            'Material': 'High-Grade Scratch-Resistant PU Leather',
            'Hardware': 'Polished Anti-Rust Gold Plated Metal',
            'Dimensions': '9.5" x 6.5" x 3.0" (Length x Height x Width)',
            'Strap': 'Adjustable Shoulder & Crossbody Chain'
        },
        colors: ['Beige Nude', 'Raven Black', 'Crimson Red'],
        isFlashSale: true,
        isTrending: false,
        isRecommended: true,
        reviews: []
    },
    {
        id: 'prod-019',
        title: 'Saeed Ghani Pure Organic Castor & Rosemary Hair Growth Serum (100ml)',
        slug: 'saeed-ghani-rosemary-hair-serum',
        category: 'beauty-care',
        brand: 'Saeed Ghani',
        price: 1250,
        oldPrice: 1750,
        discount: 28,
        rating: 4.8,
        reviewsCount: 740,
        stock: 120,
        sellerName: 'Pak Heritage Fashion',
        sellerCity: 'Karachi',
        imageUrl: 'https://images.unsplash.com/photo-1608248597359-7b7914e9f78f?auto=format&fit=crop&w=800&q=80',
        additionalImages: [],
        description: '100% natural, chemical-free cold-pressed formula infused with therapeutic grade rosemary oil and pure castor oil to stimulate hair follicles and fight dandruff.',
        specifications: {
            'Volume': '100 ml (3.38 fl. oz.) Glass Dropper Bottle',
            'Key Ingredients': 'Pure Rosemary Essential Oil, Castor Oil, Vitamin E',
            'Formulation': '100% Organic & Halal Certified',
            'Country of Origin': 'Pakistan'
        },
        colors: ['Natural Oil'],
        isFlashSale: true,
        isTrending: true,
        isRecommended: true,
        reviews: [
            { id: 'rev-11', name: 'Ayesha Siddiqui', city: 'Hyderabad', rating: 5, date: '2026-08-12', comment: 'Saw noticeable baby hair growth around hairline in 3 weeks. Saeed Ghani never disappoints!' }
        ]
    },
    {
        id: 'prod-020',
        title: 'Dawlance Air Fryer 4.5L Digital Touchscreen (Rapid Air Crisp Technology - 1400W)',
        slug: 'dawlance-air-fryer-digital-45l',
        category: 'home-kitchen',
        brand: 'Dawlance',
        price: 19499,
        oldPrice: 24500,
        discount: 20,
        rating: 4.9,
        reviewsCount: 160,
        stock: 18,
        sellerName: 'Karachi Electronics Hub',
        sellerCity: 'Karachi',
        imageUrl: 'https://images.unsplash.com/photo-1584992236310-6edddc08acff?auto=format&fit=crop&w=800&q=80',
        additionalImages: [],
        description: 'Enjoy guilt-free crispy samosas, pakoras, French fries, and grilled chicken with 85% less oil. Features 8 preset cooking menus and non-stick dishwasher-safe basket.',
        specifications: {
            'Capacity': '4.5 Liters Family Size',
            'Power': '1400 Watts Rapid Turbo Convection',
            'Temperature Range': '80°C - 200°C Adjustable',
            'Warranty': '1 Year Official Dawlance Pakistan Warranty'
        },
        colors: ['Matte Black with Gold Accents'],
        isFlashSale: false,
        isTrending: true,
        isRecommended: true,
        reviews: []
    },
    {
        id: 'prod-021',
        title: 'Anex 3-in-1 Juicer Blender & Dry Mill Grinder (Heavy Duty 600W Pure Copper Motor)',
        slug: 'anex-3in1-juicer-blender-grinder',
        category: 'home-kitchen',
        brand: 'Anex',
        price: 11999,
        oldPrice: 15500,
        discount: 22,
        rating: 4.7,
        reviewsCount: 310,
        stock: 25,
        sellerName: 'Rawalpindi Mobile Point',
        sellerCity: 'Rawalpindi',
        imageUrl: 'https://images.unsplash.com/photo-1570222094114-d054a817e56b?auto=format&fit=crop&w=800&q=80',
        additionalImages: [],
        description: 'Heavy duty stainless steel blades crush ice, grind whole Pakistani masalas, and extract fresh juices in seconds with 2 speed + pulse control.',
        specifications: {
            'Motor': '600W 100% Pure Copper Heavy Duty Motor',
            'Jars': '1.5L Unbreakable Blender Jug + Stainless Steel Grinder + Juicer',
            'Safety': 'Built-in Overheat Circuit Breaker',
            'Warranty': '2 Years Official Anex Pakistan Warranty'
        },
        colors: ['White & Silver'],
        isFlashSale: true,
        isTrending: false,
        isRecommended: true,
        reviews: []
    },
    {
        id: 'prod-022',
        title: 'CA Plus 15000 7-Star English Willow Cricket Bat (Hard Tennis / Tape Ball Edition)',
        slug: 'ca-plus-15000-cricket-bat',
        category: 'sports-fitness',
        brand: 'CA Sports',
        price: 8499,
        oldPrice: 12000,
        discount: 29,
        rating: 4.9,
        reviewsCount: 470,
        stock: 20,
        sellerName: 'Multan Sports Arena',
        sellerCity: 'Multan',
        imageUrl: 'https://images.unsplash.com/photo-1531415074868-036b1c57e329?auto=format&fit=crop&w=800&q=80',
        additionalImages: [],
        description: 'The weapon of choice for Pakistani street and club cricket superstars. Monster 40mm+ thick edges, supreme sweet-spot balance, and authentic CA hologram sticker.',
        specifications: {
            'Willow Type': 'Hand-Selected Grade 1 English Willow',
            'Edge Size': '42mm Massive Power Profile',
            'Weight': '820 - 860 grams Featherlight Pick-up',
            'Handle': 'Singapore 3-Piece Cane Handle with Spiral Grip',
            'Origin': 'Handcrafted in Sialkot, Pakistan'
        },
        colors: ['Natural Wood / Red Grip'],
        isFlashSale: true,
        isTrending: true,
        isRecommended: true,
        reviews: [
            { id: 'rev-12', name: 'Shahid Afridi Fan', city: 'Peshawar', rating: 5, date: '2026-08-17', comment: 'MashAllah what a stroke! Hit 6 sixes in yesterday tournament with this bat.' }
        ]
    },
    {
        id: 'prod-023',
        title: 'Complete Premium Adjustable Dumbbell Set 20KG with Extension Bar & Case',
        slug: 'adjustable-dumbbell-set-20kg',
        category: 'sports-fitness',
        brand: 'IronMaster',
        price: 9800,
        oldPrice: 13500,
        discount: 27,
        rating: 4.8,
        reviewsCount: 185,
        stock: 16,
        sellerName: 'Multan Sports Arena',
        sellerCity: 'Multan',
        imageUrl: 'https://images.unsplash.com/photo-1584735935682-2f2b69dff9d2?auto=format&fit=crop&w=800&q=80',
        additionalImages: [],
        description: 'Cast iron electroplated dumbbell plates with non-slip neoprene knurled grips and connector bar to convert dumbbells into a 4-foot barbell for home workouts.',
        specifications: {
            'Total Weight': '20 Kilograms (Plates: 4x2.5kg, 4x1.25kg, 4x0.5kg)',
            'Includes': '2 Dumbbell Handles + 1 Barbell Connector + 4 Spinlock Collars',
            'Case': 'Heavy Duty Molded Plastic Carrying Case'
        },
        colors: ['Electroplated Chrome Silver'],
        isFlashSale: false,
        isTrending: true,
        isRecommended: true,
        reviews: []
    },
    {
        id: 'prod-024',
        title: 'Peer-e-Kamil (S.A.W) & Abe-Hayat by Umera Ahmed (2-Book Hardcover Collector Set)',
        slug: 'peer-e-kamil-abe-hayat-umera-ahmed',
        category: 'books-stationery',
        brand: 'Ilm-o-Irfan Publishers',
        price: 2499,
        oldPrice: 3200,
        discount: 21,
        rating: 5.0,
        reviewsCount: 920,
        stock: 65,
        sellerName: 'Islamabad Gadgets Store',
        sellerCity: 'Lahore',
        imageUrl: 'https://images.unsplash.com/photo-1544947950-fa07a98d237f?auto=format&fit=crop&w=800&q=80',
        additionalImages: [],
        description: 'The masterclass Urdu literary masterpieces by legendary writer Umera Ahmed. Delivered in pristine gold-embossed hardcover binding with premium imported paper.',
        specifications: {
            'Author': 'Umera Ahmed',
            'Language': 'Urdu',
            'Binding': 'Deluxe Hardcover with Gold Foil Stamping',
            'Pages': '1280 Total Combined Pages'
        },
        colors: ['Gold Edition Hardcover'],
        isFlashSale: true,
        isTrending: true,
        isRecommended: true,
        reviews: [
            { id: 'rev-13', name: 'Maryam Noor', city: 'Quetta', rating: 5, date: '2026-08-03', comment: 'Heart-touching story. The book quality and binding is top class.' }
        ]
    },
    {
        id: 'prod-025',
        title: 'Baseus 65W GaN Fast Charger Multi-Port (2x USB-C + 1x USB-A PD 3.0)',
        slug: 'baseus-65w-gan-fast-charger',
        category: 'accessories',
        brand: 'Baseus',
        price: 6499,
        oldPrice: 8999,
        discount: 27,
        rating: 4.9,
        reviewsCount: 390,
        stock: 40,
        sellerName: 'TechZone Official Mall',
        sellerCity: 'Lahore',
        imageUrl: 'https://images.unsplash.com/photo-1583863788434-e58a36330cf0?auto=format&fit=crop&w=800&q=80',
        additionalImages: [],
        description: 'Compact Gallium Nitride (GaN 5 Pro) tech fast charges laptops (MacBook, Dell, HP), iPhones, and Samsung Galaxy at maximum speed simultaneously.',
        specifications: {
            'Total Output': '65W Max Power Delivery',
            'Ports': 'Type-C 1 (65W) + Type-C 2 (30W) + USB-A (30W)',
            'Protection': 'BPS II Safety Protection (Over-heat, Over-voltage)',
            'Warranty': '6 Months Replacement Warranty'
        },
        colors: ['Matte Black', 'Glacier White'],
        isFlashSale: false,
        isTrending: true,
        isRecommended: true,
        reviews: []
    },
    {
        id: 'prod-026',
        title: 'Remax 30,000mAh Power Bank 22.5W Super Fast Charging with LED Digital Display',
        slug: 'remax-30000mah-power-bank-22w',
        category: 'accessories',
        brand: 'Remax',
        price: 6999,
        oldPrice: 9500,
        discount: 26,
        rating: 4.8,
        reviewsCount: 460,
        stock: 55,
        sellerName: 'Rawalpindi Mobile Point',
        sellerCity: 'Rawalpindi',
        imageUrl: 'https://images.unsplash.com/photo-1609592426861-197e97491cf0?auto=format&fit=crop&w=800&q=80',
        additionalImages: [],
        description: 'Massive 30000mAh capacity will charge your smartphone 6 to 7 times. Supports Huawei 22.5W SuperCharge and iPhone PD 20W Fast Charging.',
        specifications: {
            'Battery Capacity': '30,000 mAh High-Density Polymer',
            'Display': 'Real-Time Percentage LED Display',
            'Inputs': 'Micro USB + Type-C PD Fast Input',
            'Outputs': '2x Fast USB-A + 1x Type-C Bi-directional'
        },
        colors: ['Black', 'White'],
        isFlashSale: true,
        isTrending: true,
        isRecommended: true,
        reviews: []
    },
    {
        id: 'prod-027',
        title: 'Dell UltraSharp 27" 4K USB-C Hub Monitor (IPS Black, 100% sRGB, Height Adjust)',
        slug: 'dell-ultrasharp-27-4k-monitor',
        category: 'laptops-computers',
        brand: 'Dell',
        price: 148999,
        oldPrice: 165000,
        discount: 9,
        rating: 4.9,
        reviewsCount: 75,
        stock: 6,
        sellerName: 'Islamabad Gadgets Store',
        sellerCity: 'Islamabad',
        imageUrl: 'https://images.unsplash.com/photo-1527443224154-c4a3942d3acf?auto=format&fit=crop&w=800&q=80',
        additionalImages: [],
        description: 'Experience brilliant 4K clarity with IPS Black technology delivering 2000:1 contrast ratio, 90W single-cable USB-C power delivery, and ultra-thin infinity bezel.',
        specifications: {
            'Resolution': '4K UHD 3840 x 2160 at 60Hz',
            'Color Gamut': '100% sRGB, 98% DCI-P3 Color Accuracy',
            'Ports': 'USB-C (90W PD), DisplayPort 1.4, HDMI 2.0, RJ45 LAN',
            'Warranty': '3 Years Dell Official Replacement Warranty'
        },
        colors: ['Platinum Silver'],
        isFlashSale: false,
        isTrending: false,
        isRecommended: true,
        reviews: []
    },
    {
        id: 'prod-028',
        title: 'Khaadi Men’s Pure Linen Kurta Pajama 2-Piece Suit (Charcoal Classic)',
        slug: 'khaadi-men-pure-linen-kurta-pajama',
        category: 'mens-fashion',
        brand: 'Khaadi',
        price: 6990,
        oldPrice: 8990,
        discount: 22,
        rating: 4.8,
        reviewsCount: 230,
        stock: 30,
        sellerName: 'Pak Heritage Fashion',
        sellerCity: 'Faisalabad',
        imageUrl: 'https://images.unsplash.com/photo-1598033129183-c4f50c736f10?auto=format&fit=crop&w=800&q=80',
        additionalImages: [],
        description: 'Premium tailored breathable 100% linen fabric kurta paired with classic straight-cut trousers for men. Timeless elegance and supreme comfort.',
        specifications: {
            'Fabric': '100% Pure Natural Linen',
            'Set': '2-Piece (Kurta + Straight Trouser Pajama)',
            'Stitching': 'Exquisite reinforced stitch craft'
        },
        colors: ['Charcoal Gray', 'Desert Sand', 'Navy Blue'],
        isFlashSale: false,
        isTrending: true,
        isRecommended: true,
        reviews: []
    },
    {
        id: 'prod-029',
        title: 'CeraVe Hydrating Facial Cleanser for Normal to Dry Skin with Ceramides (473ml)',
        slug: 'cerave-hydrating-facial-cleanser-473ml',
        category: 'beauty-care',
        brand: 'CeraVe',
        price: 4999,
        oldPrice: 6200,
        discount: 19,
        rating: 4.9,
        reviewsCount: 680,
        stock: 50,
        sellerName: 'TechZone Official Mall',
        sellerCity: 'Lahore',
        imageUrl: 'https://images.unsplash.com/photo-1556228720-195a672e8a03?auto=format&fit=crop&w=800&q=80',
        additionalImages: [],
        description: 'Dermatologist-recommended non-foaming hydrating lotion with 3 essential ceramides and hyaluronic acid to cleanse without stripping natural moisture.',
        specifications: {
            'Volume': '473 ml (16 fl oz) Jumbo Pump Bottle',
            'Skin Type': 'Normal to Dry / Sensitive Skin',
            'Certifications': 'Non-comedogenic, Fragrance-free, National Eczema Assoc.'
        },
        colors: ['White/Green Pump'],
        isFlashSale: true,
        isTrending: true,
        isRecommended: true,
        reviews: []
    },
    {
        id: 'prod-030',
        title: 'JBL Flip 6 Portable Waterproof Bluetooth Speaker (Original - 12H Playtime)',
        slug: 'jbl-flip-6-bluetooth-speaker',
        category: 'headphones-audio',
        brand: 'JBL',
        price: 32999,
        oldPrice: 38000,
        discount: 13,
        rating: 4.9,
        reviewsCount: 310,
        stock: 22,
        sellerName: 'Islamabad Gadgets Store',
        sellerCity: 'Islamabad',
        imageUrl: 'https://images.unsplash.com/photo-1545454675-3531b543be5d?auto=format&fit=crop&w=800&q=80',
        additionalImages: [],
        description: 'Bold JBL Original Pro Sound with 2-way speaker system, dual passive radiators, IP67 waterproof and dustproof design, and 12 hours playtime.',
        specifications: {
            'Output Power': '20W RMS Woofer + 10W RMS Tweeter',
            'Waterproof Rating': 'IP67 Waterproof & Dustproof',
            'Battery Life': '12 Hours (4800mAh Li-ion)',
            'PartyBoost': 'Pair multiple JBL PartyBoost speakers'
        },
        colors: ['Squad Camo', 'Bold Black', 'Ocean Blue', 'Fiery Red'],
        isFlashSale: false,
        isTrending: true,
        isRecommended: true,
        reviews: []
    },
    {
        id: 'prod-031',
        title: 'T-Dagger Mechanical RGB Gaming Keyboard (Blue Clicky Switches - Dustproof)',
        slug: 't-dagger-mechanical-rgb-keyboard',
        category: 'gaming',
        brand: 'T-Dagger',
        price: 6499,
        oldPrice: 8500,
        discount: 23,
        rating: 4.7,
        reviewsCount: 280,
        stock: 35,
        sellerName: 'Karachi Electronics Hub',
        sellerCity: 'Karachi',
        imageUrl: 'https://images.unsplash.com/photo-1587829741301-dc798b83add3?auto=format&fit=crop&w=800&q=80',
        additionalImages: [],
        description: 'Tactile blue mechanical switches with satisfying click sound, rainbow RGB backlighting with 9 dynamic effects, full anti-ghosting keys, and double-shot keycaps.',
        specifications: {
            'Switches': 'Outemu Dustproof Blue Mechanical Switches (50M Clicks)',
            'Keys': '104 Keys Full Size with Numeric Keypad',
            'Cable': '1.8m Braided USB Gold Plated Cable'
        },
        colors: ['Black'],
        isFlashSale: true,
        isTrending: false,
        isRecommended: true,
        reviews: []
    },
    {
        id: 'prod-032',
        title: 'Oxford Urdu-English Progressive Dictionary (Latest Comprehensive Edition)',
        slug: 'oxford-urdu-english-dictionary',
        category: 'books-stationery',
        brand: 'Oxford University Press',
        price: 1850,
        oldPrice: 2400,
        discount: 22,
        rating: 4.9,
        reviewsCount: 410,
        stock: 80,
        sellerName: 'Pak Heritage Fashion',
        sellerCity: 'Karachi',
        imageUrl: 'https://images.unsplash.com/photo-1497633762265-9d179a990aa6?auto=format&fit=crop&w=800&q=80',
        additionalImages: [],
        description: 'The standard reference dictionary for students, teachers, and professionals across Pakistan with over 50,000 words, idioms, phrases, and Urdu script pronunciation guides.',
        specifications: {
            'Publisher': 'Oxford University Press Pakistan',
            'Edition': 'Latest Revised Edition',
            'Format': 'Hardback with protective plastic jacket'
        },
        colors: ['Standard Navy Blue'],
        isFlashSale: false,
        isTrending: false,
        isRecommended: true,
        reviews: []
    }
];
